= Neo4j Asciidoctor Extensions
:uri-neo4j: https://neo4j.com

image:https://github.com/neo4j-contrib/neo4j-asciidoctor-extensions/workflows/CI/badge.svg[CI,link=https://github.com/neo4j-contrib/neo4j-asciidoctor-extensions/actions?query=workflow%3ACI]

This repository contains Asciidoctor extensions made by {uri-neo4j}[Neo4j] for processing and publishing AsciiDoc content.

== Install

[source,console]
----
$ gem install neo4j-asciidoctor-extensions
----

== Usage

=== CLI

[source,console]
----
$ asciidoctor -r neo4j/asciidoctor/extensions doc.adoc
----

=== API

[source,ruby]
----
require 'neo4j/asciidoctor/extensions'
----

In addition, you can require individual extension:

[source,ruby]
----
require 'neo4j/asciidoctor/extensions/revealjs_linear_navigation'
----

See below for the complete list of extensions.

== Extensions

The Ruby gem contains 6 distinct extensions:

=== `course_document_attributes`

A postprocessor that adds attributes about the course.

=== `cypher_syntax_role`

A tree processor that adds a role on code blocks using "cypher-syntax" as a language.

*Usage:*

[source]
....
[source,cypher-syntax]
----
()
(p)
(l)
(n)
----
....

=== `document_metadata_generator`

A postprocess that generates a metadata file (in YAML format) from a list of document attributes.

*Usage:*

.file.adoc
[source,adoc]
----
:document-metadata-attrs-include: author,slug,parent-path,tags*,taxonomies*<>
:tags: intro,course
:taxonomies: os=linux,programming_language=java,neo4j_version=3-5;3-6
:slug: intro-neo4j-4-0
:parent_path: /intro
----

.file.yml
[source,adoc]
----
slug: intro-neo4j-4-0
parent_path: /intro
author:
  name: Michael Hunger
  first_name: Michael
  last_name: Hunger
  email: michael.hunger@neotechnology.com
tags:
  - intro
  - course
taxonomies:
  - key: os
    values:
      - linux
  - key: programming_language
    values:
      - java
  - key: neo4j_version
    values:
      - 3-5
      - 3-6
----

=== `inline_highlighter_rouge`

Inline syntax highlighter based on Rouge.
It applies syntax highlighting on both monospaced text cypher and `src` inline macro:

*Usage:*

[source,adoc]
----
[src-cypher]`MATCH (c:Customer {customerName: 'ABCCO'}) RETURN c.BOUGHT.productName`

src:cypher[MATCH (c:Customer {customerName: 'ABCCO'}) RETURN c.BOUGHT.productName]
----

=== `revealjs_linear_navigation`

A tree process that "flatten" a reveal.js presentation to use a linear navigation.
By default, the reveal.js converter will use a vertical navigation for the second levels of section titles (and below).
This extension will effectively prevent that by using only first level section titles.

=== `revealjs_speaker_notes_aggregator`
A tree processor that aggregates multiple `[.notes]` blocks in a section (slide).

*Usage:*

[source,adoc]
----
== Introduction

[.notes]
--
This is a speaker note.
--

Hello!

[.notes]
--
This is another speaker note.
--
----

== Release

The release process is automated and relies on GitHub Actions.
We are using the :robot: `neo4j-oss-build` account to published on https://rubygems.org/gems/neo4j-asciidoctor-extensions.

The `RUBYGEMS_API_KEY` secret is configured on GitHub.
See the `.github/workflows/release.yml` file for details.

The release will be performed when a tag is pushed, the procedure is:

. Edit `neo4j-asciidoctor-extensions.gemspec` and update the version number `s.version`
. Run `bundle exec rake` to make sure that everything is working
. Commit both `neo4j-asciidoctor-extensions.gemspec` and `Gemfile.lock` files
. Tag the version using `git tag vx.y.z` (don't forget the `v` prefix and replace `x.y.z` with an actual version)
. Push your changes with the tag: `git push origin master --tags`

